name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: set up python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.9

    - name: Install dependencies
      run: make install

    - name: lint
      run: make lint

    - name: test
      run: make test